[NR_INDEKSU]
name = "ImiÄ™ Nazwisko"
color = "blue"
k1 = 1.1
k2 = 2.2
k3 = 3.3
code_link = "https://github.com/LukeMech/STUDIA_TMiPA_Projects/tree/main/R2S1_P2"
replace_ai_1 = "Opis odpowiedzi skokowej dla wymuszenia u0(t) = ... "
